### ISSUE TITLE
I used cutup for training, but an error occurred. Could you tell me why? I'm hurry to get the result

### ISSUE THREAD

**Issue by YangJay2004** [mobulan/MPSA#1]
============================     Start Training     ============================
Train  1 /50 :   0%|                                                                         | 0/78 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/AIC/MPSA/main.py", line 363, in <module>
    main(config)
  File "/mnt/AIC/MPSA/main.py", line 138, in main
    train_accuracy = train_one_epoch(config, model, criterion, train_loader, optimizer,
  File "/mnt/AIC/MPSA/main.py", line 207, in train_one_epoch
    logits = model(x, y)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/AIC/MPSA/models/mps.py", line 141, in forward
    loss_ce = self.ce(x, label)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/timm/loss/cross_entropy.py", line 22, in forward
    nll_loss = -logprobs.gather(dim=-1, index=target.unsqueeze(1))
RuntimeError: gather(): Expected dtype int64 for index
Train  1 /50 :   0%|                                                                         | 0/78 [00:04<?, ?it/s]
(myconda) root@wyexnr:/mnt/AIC/MPSA#

**Comment by mobulan** [comment]
This may caused by the lower version of pytorh or higher version of timm. pytorch required for 1.13.0 or higher for the support of soft labels of cross entropy. timm required for 0.6.13 or lower version. Try these version may solve you problem.

**Comment by YangJay2004** [comment]
thank you so much!!!!
